name: Build agent

on:
  workflow_call:
    inputs:
      agent-ref:
        required: true
        default: main
        type: string
        description: 'The ref (branch, SHA, tag?) to run the tests on'
      gradle-cache-read-only:
        required: false
        default: true
        type: boolean
        description: 'Whether the gradle cache should be read only'
jobs:
  # build the agent and saves Gradle's cache so all modules can use the cache
  build-agent:
    runs-on: ubuntu-20.04
    env:
      # we use this in env var for conditionals (secrets can't be used in conditionals)
      AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - name: Checkout Java agent
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v4
        with:
          ref: ${{ inputs.agent-ref }}

      - name: Configure AWS Credentials
        if: ${{ env.AWS_KEY != '' }}
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # pin@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          gradle-cache-read-only: ${{ inputs.gradle-cache-read-only }}

      - name: Build agent
        run: ./gradlew $GRADLE_OPTIONS clean jar

      - name: Cache agent
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # pin@v4
        with:
          path: /home/runner/work/newrelic-java-agent/newrelic-java-agent/newrelic-agent/build/newrelicJar/newrelic.jar
          key: agent-jar-${{ github.run_id }}
